version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "dev"
    labels:
      - "external-dependency"

  - package-ecosystem: "npm"
    directory: "/angular-demo"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "dev"
    labels:
      - "external-dependency"

  - package-ecosystem: "npm"
    directory: "/react-demo"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    target-branch: "dev"
    labels:
      - "external-dependency"