version: 2.1
orbs:
    gh: circleci/github-cli@1.0.3
jobs:
    build:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: yarn
            - run:
                  name: Verify Artifacts
                  command: yarn test

    publish:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - run:
                name: Authenticate with registry
                command: |
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                  echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                name: Publish @pxblue/mapbox
                command: |
                  yarn publish:package -b $CIRCLE_BRANCH

    tag:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - checkout
            - gh/setup
            - run:
                name: Tag @pxblue/mapbox
                command: |
                  yarn tag:package -b $CIRCLE_BRANCH

workflows:
    version: 2
    mapbox:
        jobs:
            - build
            - publish:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - dev
            - tag:
                requires:
                   - publish
                filters:
                    branches:
                        only:
                            - master
